#!/bin/sh

#FIXME This script does a small amount of processing on the last line of a log,
#  but I haven't hardened the string processing (e.g., to protect against code
#  injection on the build server via an engineered build failure..).

#An assignment and an axiom?
SUCCESS="MIRAGE WORKS"

cat <<EOF
<table>
<tr><td align=middle>Status</td><td align=middle>Target</td><td>Last line of log</td></tr>
<tr><th colspan=3></th></tr>
EOF
for FILE in `ls logs/mirage*`
do
  ACC='<tr><td align=middle '
  LOGNAME=`basename ${FILE}`
  ENDING=`tail -n 1 $FILE | sed 's/[ \n]*$//'`
  echo "${ENDING}" | grep -q "${SUCCESS}"
  if [ "$?" -eq 0 ]
  then
    ACC="${ACC}"'color="#00FF00">OK'
  else
    ACC="${ACC}"'color="#FF0000">:('
  fi
  echo "${ACC}"'</td><td>'"${LOGNAME}"'</td><td>'"${ENDING}"
  echo '</td></tr>'
done
echo "</table>"
