#!/bin/sh -x

sudo docker.io pull avsm/docker-opam

git pull --no-edit

for script in mirage-www mirage-skeleton; do
  for distro in ubuntu-trusty centos-7; do
    for ver in 4.01.0 4.02.1; do
      ./build.sh $distro-$ver $script 2>&1 | tee logs/$script-$distro-$ver
    done
  done
done

METADATA="Latest build logs (as of $(date))"
POLITE_NOTICE='<!--THIS FILE IS AUTOMATICALLY GENERATED BY cron.sh. DO NOT EDIT-->'

cat > logs/README.html <<EOF
<html><head><title>${METADATA}</title></head>
${POLITE_NOTICE}
<body><h2>${METADATA}</h2>
EOF
./analyse_logs >> logs/README.html
echo '</body></html>' >> logs/README.html

git add logs/
git commit -m "Sync logs"
git push
