#!/bin/sh -x
#
# Update the sources of the openmirage.org site with the latest build info from
# is-mirage-broken. Generates a PR to mirage/mirage-www (from which the
# openmirage.org site is produced) if the most recent build info (generated by
# is-mirage-broken) differs (modulo the date in the title) from what's currently
# shown on openmirage.org.
#
# Nik Sultana, Cambridge University Computer Lab, November 2014

# FIXME how to regenerate the running site?

# If we don't have a copy of bactrian's fork of mirage-www, then clone it.
if [ ! -d mirage-www ]
then
  # FIXME need to fork mirage-www to bactrian's account -- but only need to do
  # this once, then need to keep merging mirage-www/master into it
  github fork

  # FIXME need to clone from bactrian's account
  git clone git://github.com/bactrian/mirage-www
# FIXME, use git protocol or HTTPS? -- git clone https://github.com/mirage/mirage-www
  # FIXME check that clone was successful -- if not then die
fi

cd mirage-www

git pull
# FIXME check that pull was successful -- if not then die, otherwise we'll be
# working with stale data. -- could use parameter to "sh" for this, I think --
# but would this fail at *any* non-zero exit status? That would be buggered up
# by "diff" below, for example.
# FIXME check if we've already set remote upstream
git remote upstream git://github.com/mirage/mirage-www
# FIXME bring bactrian's fork up to date
git fetch upstream master
git merge upstream/master

# Compare mirage-www/tmpl/wiki/is_mirage_broken.md with logs/README.md
# (modulo timestamp). Only proceed if something's changed.
true && diff -q <(sed -e '1d' ../logs/README.md) <(sed -e '1d' tmpl/wiki/is_mirage_broken.md)
if [ $? -eq 1 ]
then
  # Make sure that TMPFILE is a not-yet-existing file
  TMPFILE=
  while [ -z "${TMPFILE}" ]
  do
    PROPOSAL=/tmp/cronsh-${RANDOM}
    if [ ! -f "${PROPOSAL}" ]
    then
      TMPFILE="${PROPOSAL}"
    fi
  done

  cp ../logs/README.md tmpl/wiki/is_mirage_broken.md
  # FIXME replace with actual date/time values in perl regex:
  #perl -pe 's/date \(\d+, \d+, \d+, \d+, \d+\);(\(\*NOTE: is-mirage-broken:marker\*\))/date (YEAR, MONTH, DAY, HOUR, MINUTE);$1/' src/data.ml > "${TMPFILE}"
  perl -ne '
    if ($_ =~ /^(.*)date.+(\(\*NOTE is-mirage-broken:marker\*\))/)
    {
      my ($minute, $hour, $day, $month, $year) = (localtime)[1,2,3,4,5];
      printf ("%sdate (%04d, %02d, %02d, %02d, %02d) %s\n", $1,
        $year + 1900, $month + 1, $day, $hour, $minute, $2);
    } else {
      print "$_";
    }' src/data.ml > "${TMPFILE}"
  mv "${TMPFILE}" src/data.ml

  # FIXME consistently quote TMPFILE and other files, as above, or not?

  git commit tmpl/wiki/is_mirage_broken.md src/data.ml -m "updated build status at $(date);"
  git push
  # FIXME make PR from bactrian/master to mirage-www/master
  github pull request
  # FIXME check outcome of pull request?
fi

cd ..
