#!/bin/sh -ex

if [ -z "${MIRAGE_APPLICATION}" ]
then
  >&2 echo "\$MIRAGE_APPLICATION has not been defined."
  exit 1
fi

opam remote add mirage git://github.com/mirage/mirage-dev
opam update -u
opam installext -j 3 mirage ssl
eval `opam config env`
git clone git://github.com/mirage/mirage-${MIRAGE_APPLICATION}
cd mirage-${MIRAGE_APPLICATION}
export MODE=unix
make configure
make depend
make build
export MODE=xen
make configure
make depend
make build
echo MIRAGE WORKS
