#!/bin/sh -ex

#sudo chown -R opam:opam /home/opam
#cd /home/opam

opam remote add mirage git://github.com/mirage/mirage-dev
opam installext -j 3 mirage
eval `opam config env`
git clone git://github.com/mirage/mirage-www
cd mirage-www
export MODE=unix
make configure && make build
echo MIRAGE WORKS
