#!/bin/sh -ex

set -e

opam remote add mirage git://github.com/mirage/mirage-dev
opam update -u
opam installext -j 3 mirage ssl
eval `opam config env`
git clone git://github.com/mirage/mirage-www
cd mirage-www
export MODE=unix
make configure
make depend
make build
export MODE=xen
make configure
make depend
make build
echo MIRAGE WORKS
